Get things mostly working again.
First of all, I had to blow away my node_modules/ directory
and rerun 'npm install' to download everything again. This
had the side effect of rewriting package-lock.json.

I also had to manually install @babel/runtime to fix a bunch of
'TypeError: _interopRequireDefault is not a function' errors
when running 'npm run test:unit'.

'npm run test:e2e' is also broken. I think that Nightwatch
is incompatible with the current version of Chrome. Using
chromedriver 94.0.4606.61, I see 'Error while running
.getLogContents() protocol action: Unknown command 404 Not
Found'. I tried updating to nightwatch@1.7.11, the latest
stable version, but it's still broken.

I'm intentionally updating as few packages as possible,
since when I tried that I ended up in a nightmare world of
Babel-related errors. Updating Vue and/or Vuetify also
causes a bunch of unit test failures and spacing changes.

And just to mention it, upgrading Jest is also a bad idea.
When using a version later than 24.9.0, calling jest.mock()
from outside of a test (e.g. in src/firebase/mock.ts)
apparently results in a 'Do not import `@jest/globals`
outside of the Jest test environment' error. Per
https://github.com/facebook/jest/issues/10147 (now closed),
it doesn't look like Facebook has any plans to try to fix
this.